server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: postgres
    password: lehre
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob.non-contextual-creation: true
        show_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    com.lehre: TRACE
