server:
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/course
    username: root
    password: lehre
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob.non-contextual-creation: true
        show_sql: true
