server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: lehre
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob.non-contextual-creation: true
        show_sql: true
